# Generated by Django 5.0.6 on 2025-05-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('flavor_profile', models.TextField(help_text='Np. Czarna porzeczka, daktyle, pomarańcza krwista')),
                ('region', models.CharField(max_length=100)),
                ('altitude', models.CharField(help_text='Np. 1800+ m n.p.m.', max_length=50)),
                ('variety', models.CharField(help_text='Np. SL34, SL28', max_length=100)),
                ('process', models.CharField(help_text='Np. Washed, Natural', max_length=50)),
                ('roast_date', models.DateField(help_text='Data palenia')),
                ('roast_profile', models.CharField(help_text='Np. Jasny, do metod alternatywnych', max_length=100)),
                ('weight', models.CharField(help_text='Np. 250g', max_length=20)),
                ('roaster', models.CharField(help_text='Np. Friedhats z Amsterdamu', max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('farm', models.CharField(blank=True, help_text='Nazwa farmy/spółdzielni', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Coffees',
            },
        ),
        migrations.CreateModel(
            name='Brewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('aeropress', 'AeroPress'), ('chemex', 'Chemex'), ('drip', 'Drip/Pour Over'), ('espresso', 'Espresso'), ('french_press', 'French Press'), ('moka_pot', 'Moka Pot'), ('siphon', 'Siphon'), ('v60', 'V60'), ('kalita', 'Kalita Wave'), ('other', 'Inna')], max_length=50)),
                ('grind_size', models.CharField(help_text='Np. Średnio drobny, 2.2 na EK43', max_length=50)),
                ('ratio', models.CharField(help_text='Np. 1:15', max_length=20)),
                ('recipe', models.TextField(blank=True, help_text='Przepis na parzenie')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brewing_methods', to='store.coffee')),
            ],
        ),
    ]
